name: Deploy Terraform

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Python for Testing
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: pytest

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 6: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 8: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 9: Terraform Apply (only if PR is merged)
      - name: Terraform Apply
        if: github.event.pull_request.merged == true
        run: terraform apply -auto-approve
