name: Deploy Terraform

on:
  pull_request:
      types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Python for Testing
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: pytest

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 6: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Check for destroy key
        working-directory: ./terraform
        id: check_destroy
        run: |
          DESTROY=$(jq -r '.destroy' config.json || echo "false")
          if [ "$DESTROY" == "true" ]; then
            echo "Destroy key is true. Proceeding to destroy infrastructure."
            echo "action=destroy" >> $GITHUB_ENV
          else
            echo "Destroy key is false. Proceeding with other actions."
            echo "action=apply" >> $GITHUB_ENV

      - name: Terraform Destroy
        working-directory: ./terraform
        if: env.action == 'destroy'
        run: |
          terraform init
          terraform destroy -auto-approve

      # Step 5: Stop the workflow after destroy
      - name: Stop Workflow After Destroy
        working-directory: ./terraform
        if: env.action == 'destroy'
        run: |
          echo "Destroy completed. Stopping the workflow."
          exit 0

      # Step 8: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      # Step 9: Terraform Apply (only if PR is merged)
      - name: Terraform Apply
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Terraform Destroy on Apply Failure
        if: failure() # directive ensures that this step runs only if the previous steps (like terraform apply) fail.
        working-directory: ./terraform
        run: terraform destroy -auto-approve